### ISSUE TITLE
loremIpsum method does not exists

### ISSUE THREAD

**Issue by fables-alive-games** [pabrrs/TFaker#2]
loremIpsum method does not exists albeit explained in readme.md

**Comment by pabrrs** [comment]
Hey @kursatturkay, thank you for reporting, and sorry for the delay.

I've open a PR to fix it, could you make a review ?

[PR:3](https://github.com/pabrrs/TFaker/pull/3)

**Comment by pabrrs** [comment]
Fixed #3
